# Generated by Django 4.0.6 on 2023-11-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_employe_categ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['id'], 'verbose_name': 'Nombre', 'verbose_name_plural': 'Nombres'},
        ),
    ]
